# Site settings
title: Irmas Reise
email: moritz.stoltenburg@web.de
description: > # this means to ignore newlines until "baseurl:"
  Eindrücke einer Reise durch Australien und Neuseeland mit Kind.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mstoltenburg.github.io" # the base hostname & protocol for your site
twitter_username: mstoltenburg
github_username:  mstoltenburg
timezone: Europe/Berlin
exclude:
  - assets/images/_fullsize
  - bower.json
  - bower_components/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - mstoltenburg.sublime-project
  - mstoltenburg.sublime-workspace
  - node_modules/
  - package.json
  - README.md
  - vendor/
categories:
  - Elternzeit
  - Neuseeland


# Build settings
# markdown: kramdown | redcarpet
markdown: kramdown

permalink: /:year/:month/:day/:title/

gems:
  - jemoji
